package cornell.cs3300.nosql;

import com.google.code.morphia.Key;

import cornell.cs3300.nosql.pojos.Candy;
import cornell.cs3300.nosql.pojos.ClusterCentroid;
import cornell.cs3300.nosql.pojos.Customer;

/**
 * Service for reporting and retrieving interactions between customers and
 * candy.
 */
public interface ReportingService {

	/**
	 * The user rates a candy
	 * 
	 * @param userId
	 * @param candyId
	 * @param rating
	 *            0 to 1
	 */
	void rateCandy(Key<Customer> userId, Key<Candy> candyId, float rating) throws ServerException;

	/**
	 * The user purchases the candy
	 * 
	 * @param userId
	 * @param candyId
	 */
	void purchaseCandy(Key<Customer> userId, Key<Candy> candyId) throws ServerException;

	/**
	 * Gets the names of all the candies purchased by the given user
	 * 
	 * @param userId
	 * @return
	 */
	String[] getCandyPurchased(Key<Customer> userId) throws ServerException;

	/**
	 * Runs the candy-preference clustering algorithm.
	 * 
	 * @param numSeeds the number of clustering seeds
	 * @param minimumRating the minimum rating needed for a cluster point to be considered
	 * @param iterations the number of k-means iterations to do
	 */
	void runClustering(int numSeeds, float minimumRating, int iterations) throws ServerException;

	/**
	 * Gets the resulting cluster points generated by the clustering.
	 * @return
	 */
	ClusterCentroid[] getPreferenceClusters() throws ServerException;
}
